[build]
  base    = ""
  publish = "public"
  command = "yarn build"
  environment = { GATSBY_CPU_COUNT = "1" }

[context.production]
  environment = { GA_TRACKING_ID = "UA-131523635-1" }

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/photos/"
  to = "/produits/"

[[redirects]]
  from = "/photos/:slug/"
  to = "/produits/:slug/"