[build]
  base    = ""
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/photos/"
  to = "/produits/"

[[redirects]]
  from = "/photos/:slug/"
  to = "/produits/:slug/"