name: Bundlewatch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn
    - run: yarn bundlewatch
      env:
        BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
