name: Lighthouse

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - run: sleep 360  # 6 mins in seconds
      if: ${{ github.event_name == 'push' }}
    - name: Wait for deploy
      if: ${{ github.event_name == 'pull_request' }}
      uses: maddox/actions/wait-for-200@master
      env:
        URL: 'https://deploy-preview-${{ github.event.pull_request.number }}--carriere-alla.netlify.app'
        SECONDS_BETWEEN_CHECKS: 20
        MAX_TRIES: 30
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.carriere-alla.fr'
        netlify_site: 'carriere-alla.netlify.app'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
