name: Lighthouse

on:
  pull_request:
    branches: 
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for deploy
      run: sleep 300  # 5 mins in seconds
    - name: Lighthouse Audit
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://www.carriere-alla.fr'
        netlify_site: 'carriere-alla.netlify.com'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
