name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
        - eslint
        - prettier

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn
    - run: |
        yarn lint:${{ matrix.linter }}
