name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
        - eslint
        - prettier

    steps:
    - uses: actions/checkout@v2

    # Setup node based on .nvmrc
    # https://github.com/actions/setup-node/issues/32#issuecomment-539794249
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm
    - uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - run: yarn
    - run: |
        yarn lint:${{ matrix.linter }}
